# Generated by Django 5.2.17 on 2026-09-11 18:35

import clinic.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('specialization', models.CharField(max_length=160)),
                ('biography', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('expertise', models.TextField(blank=True)),
                ('experience', models.PositiveSmallIntegerField(default=0)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{8,15}$', 'Enter 8–15 digits, optionally starting with + (country code).')])),
                ('email', models.EmailField(max_length=254)),
                ('clinic_name', models.CharField(max_length=160)),
                ('clinic_address', models.TextField()),
                ('profile_image', models.ImageField(blank=True, upload_to=clinic.models.photo_path)),
                ('website_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{8,15}$', 'Enter 8–15 digits, optionally starting with + (country code).')])),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='clinic.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='clinic.doctor')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)])),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinic.doctor')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{8,15}$', 'Enter 8–15 digits, optionally starting with + (country code).')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='clinic.doctor')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('duration', models.PositiveSmallIntegerField(default=30)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField(blank=True, max_length=1500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='PENDING', max_length=12)),
                ('token_digest', models.CharField(editable=False, max_length=64)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.patient')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1500)),
                ('icon', models.CharField(choices=[('heart', 'Heart'), ('pulse', 'Pulse'), ('shield', 'Shield'), ('plus', 'Medical cross')], default='heart', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinic.doctor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_public', True)), fields=('is_public',), name='one_public_doctor'),
        ),
        migrations.AddConstraint(
            model_name='doctorleave',
            constraint=models.UniqueConstraint(fields=('doctor', 'date'), name='unique_doctor_leave'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_positive_period'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__lte', 6), ('slot_duration__gte', 5), ('slot_duration__lte', 180)), name='schedule_valid_values'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['doctor', 'name'], name='clinic_pati_doctor__7fb945_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date', 'status'], name='clinic_appo_doctor__51425a_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_occupied_doctor_slot'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW'])), name='valid_appointment_status'),
        ),
    ]
